#!/usr/bin/env python3
import argparse
import json
import os
import shutil
import subprocess
import sys
import time


def proxy_precheck(proxy, timeout):
    proc = subprocess.run(
        [
            "curl",
            "-x",
            proxy,
            "-sS",
            "--connect-timeout",
            str(timeout),
            "--max-time",
            str(timeout),
            "https://api64.ipify.org",
        ],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        return False, proc.stderr.strip() or f"curl exited with {proc.returncode}"
    return True, proc.stdout.strip()


def load_json(path):
    with open(path, "r", encoding="utf-8") as file:
        return json.load(file)


def node_meta(node):
    return {
        "id": node["id"],
        "type": node.get("type", "node"),
        "name": node.get("name", ""),
        "host": node.get("host") or node.get("panel_host") or node.get("server", ""),
        "port": node.get("port") or node.get("panel_port") or node.get("server_port", ""),
        "proxy": node["proxy"],
    }


def sanitize_service_group(group):
    sanitized = {}
    if not isinstance(group, dict):
        return sanitized
    allowed = ("name", "status", "region", "country_code", "currency_code", "unlock_type", "display_value")
    for key, value in group.items():
        if not isinstance(value, dict):
            continue
        if str(value.get("status", "")).lower() != "yes":
            continue
        item = {field: value[field] for field in allowed if value.get(field) not in (None, "")}
        if item:
            sanitized[key] = item
    return sanitized


def sanitize_result(result):
    node = result.get("node") or {}
    sanitized = {
        "node": {
            "id": node.get("id"),
            "type": node.get("type", "node"),
            "checked_at": node.get("checked_at"),
        }
    }
    if node.get("duration") is not None:
        sanitized["node"]["duration"] = node.get("duration")
    if result.get("media"):
        sanitized["media"] = sanitize_service_group(result.get("media"))
    if result.get("ai"):
        sanitized["ai"] = sanitize_service_group(result.get("ai"))
    if result.get("other"):
        sanitized["other"] = sanitize_service_group(result.get("other"))
    if result.get("error"):
        sanitized["error"] = "check_failed"
    return sanitized


def write_json(path, data):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    tmp_path = f"{path}.tmp"
    with open(tmp_path, "w", encoding="utf-8") as file:
        json.dump(data, file, ensure_ascii=False, indent=2, sort_keys=True)
        file.write("\n")
    os.replace(tmp_path, path)


def run_check(node, check_script, menu, timeout, precheck_timeout):
    ok, precheck = proxy_precheck(node["proxy"], precheck_timeout)
    if not ok:
        return {
            "node": node_meta(node),
            "error": f"proxy precheck failed: {precheck}",
        }

    meta = node_meta(node)
    env = os.environ.copy()
    env.update(
        {
            "UNLOCK_NODE_ID": str(meta["id"]),
            "UNLOCK_NODE_NAME": meta["name"],
            "UNLOCK_NODE_HOST": meta["host"],
            "UNLOCK_NODE_PORT": str(meta["port"]),
            "UNLOCK_NODE_PROXY": node["proxy"],
            "UNLOCK_NODE_OUTBOUND_IP": precheck,
            "UNLOCK_MENU": str(menu),
        }
    )
    proc = subprocess.run(
        ["bash", check_script, "-J", "-P", node["proxy"]],
        input=f"{menu}\n",
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
        timeout=timeout,
        check=False,
    )
    if proc.returncode != 0:
        error_detail = proc.stderr.strip() or proc.stdout.strip()[-2000:] or f"check exited with {proc.returncode}"
        return {
            "node": node_meta(node),
            "error": error_detail,
        }
    try:
        result = json.loads(proc.stdout)
        result.setdefault("node", {}).setdefault("type", node.get("type", "node"))
        return result
    except json.JSONDecodeError as exc:
        return {
            "node": node_meta(node),
            "error": f"invalid json output: {exc}",
            "raw": proc.stdout[-2000:],
        }


def main():
    parser = argparse.ArgumentParser(description="Run unlock checks for generated AnyTLS local proxies.")
    parser.add_argument("--map", default="/root/node/anytls-proxies.json", help="proxy map generated by generate_anytls_singbox.py")
    parser.add_argument("--check", default="/root/node/check.sh", help="check.sh path")
    parser.add_argument("--menu", default="0 11", help="check menu numbers, default runs Globe and AI")
    parser.add_argument("--output-dir", default="/root/node/unlock-results", help="directory for per-node json results")
    parser.add_argument("--v2board-output", default="/www/wwwroot/v2board/storage/app/unlock-results/all.json", help="copy sanitized summary json here for V2Board frontend API, empty disables copy")
    parser.add_argument("--public-output", default="", help="write sanitized summary json here for read-only exposure, empty disables it")
    parser.add_argument("--full-v2board-output", action="store_true", help="copy full summary to --v2board-output instead of sanitized summary")
    parser.add_argument("--no-summary-output", action="store_true", help="do not write all.json/public.json or copy summary outputs")
    parser.add_argument("--node-id", default="", help="only check the node with this id")
    parser.add_argument("--node-name", default="", help="only check nodes whose name contains this text")
    parser.add_argument("--limit", type=int, default=0, help="limit number of nodes, 0 means all")
    parser.add_argument("--start", type=int, default=0, help="start offset in proxy map")
    parser.add_argument("--timeout", type=int, default=600, help="timeout seconds for each node check")
    parser.add_argument("--precheck-timeout", type=int, default=15, help="timeout seconds for proxy connectivity precheck")
    args = parser.parse_args()

    nodes = load_json(args.map)
    if args.node_id:
        nodes = [node for node in nodes if str(node.get("id", "")) == str(args.node_id)]
    if args.node_name:
        nodes = [node for node in nodes if args.node_name in str(node.get("name", ""))]
    if args.start:
        nodes = nodes[args.start :]
    if args.limit:
        nodes = nodes[: args.limit]
    os.makedirs(args.output_dir, exist_ok=True)

    all_results = []
    for index, node in enumerate(nodes, 1):
        print(f"[{index}/{len(nodes)}] checking {node['id']} {node['name']} via {node['proxy']}", file=sys.stderr)
        started_at = int(time.time())
        result = run_check(node, args.check, args.menu, args.timeout, args.precheck_timeout)
        result.setdefault("node", {}).update(
            {
                "id": node["id"],
                "type": node.get("type", "node"),
                "checked_at": int(time.time()),
                "duration": int(time.time()) - started_at,
            }
        )
        all_results.append(result)
        # Codex改动：通用协议检测时按协议拆分文件名，避免不同表相同 ID 覆盖。
        node_type = node.get("type", "node")
        output_path = os.path.join(args.output_dir, f"{node_type}-{node['id']}.json")
        write_json(output_path, result)

    if args.no_summary_output:
        return

    summary_path = os.path.join(args.output_dir, "all.json")
    write_json(summary_path, all_results)
    sanitized_results = [sanitize_result(result) for result in all_results]
    sanitized_path = os.path.join(args.output_dir, "public.json")
    # Codex改动：生成脱敏 public.json，只保留前端展示需要的字段，避免暴露出口 IP、代理端口、host 和原始检测文本。
    write_json(sanitized_path, sanitized_results)
    if args.public_output:
        shutil.copyfile(sanitized_path, args.public_output)
    # Codex改动：默认同步脱敏结果到 V2Board storage，避免 PHP-FPM 无法读取 /root 目录，也减少公开面。
    if args.v2board_output:
        os.makedirs(os.path.dirname(args.v2board_output), exist_ok=True)
        shutil.copyfile(summary_path if args.full_v2board_output else sanitized_path, args.v2board_output)
    print(summary_path)


if __name__ == "__main__":
    main()
